const TOGGLE_IS_USER_AUTHENTICATED = 'app/TOGGLE_IS_USER_AUTHENTICATED';
const TOGGLE_IS_USER_AUTHENTICATED_SUCCESS =
  'app/TOGGLE_IS_USER_AUTHENTICATED_SUCCESS';

export { TOGGLE_IS_USER_AUTHENTICATED, TOGGLE_IS_USER_AUTHENTICATED_SUCCESS };
