// register user actions
const REGISTER_USER_REQUEST = 'user/REGISTER_USER_REQUEST';
const REGISTER_USER_REQUEST_START = 'user/REGISTER_USER_REQUEST_START';
const REGISTER_USER_REQUEST_SUCCESS = 'user/REGISTER_USER_REQUEST_SUCCESS';
const REGISTER_USER_REQUEST_FAILED = 'user/REGISTER_USER_REQUEST_FAILED';
// user logout action
const USER_LOGOUT = 'user/USER_LOGOUT';
// add offer to user offers
const ADD_USER_OFFER_REQUEST = 'user/ADD_USER_OFFER_REQUEST';
const ADD_USER_OFFER_REQUEST_START = 'user/ADD_USER_OFFER_REQUEST_START';
const ADD_USER_OFFER_REQUEST_FAILED = 'user/ADD_USER_OFFER_REQUEST_FAILED';
const ADD_USER_OFFER_REQUEST_SUCCESS = 'user/ADD_USER_OFFER_REQUEST_SUCCESS';
// remove offer from the user offers
const REMOVE_USER_OFFER_REQUEST = 'user/REMOVE_USER_OFFER_REQUEST';
const REMOVE_USER_OFFER_REQUEST_START = 'user/REMOVE_USER_OFFER_REQUEST_START';
const REMOVE_USER_OFFER_REQUEST_SUCCESS =
  'user/REMOVE_USER_OFFER_REQUEST_SUCCESS';
const REMOVE_USER_OFFER_REQUEST_FAILED =
  'user/REMOVE_USER_OFFER_REQUEST_FAILED';

export {
  REGISTER_USER_REQUEST,
  REGISTER_USER_REQUEST_START,
  REGISTER_USER_REQUEST_SUCCESS,
  REGISTER_USER_REQUEST_FAILED,
  USER_LOGOUT,
  ADD_USER_OFFER_REQUEST,
  ADD_USER_OFFER_REQUEST_START,
  ADD_USER_OFFER_REQUEST_SUCCESS,
  ADD_USER_OFFER_REQUEST_FAILED,
  REMOVE_USER_OFFER_REQUEST,
  REMOVE_USER_OFFER_REQUEST_START,
  REMOVE_USER_OFFER_REQUEST_SUCCESS,
  REMOVE_USER_OFFER_REQUEST_FAILED,
};
