// get all tags
const GET_TAGS_REQUEST = 'tag/GET_TAGS_REQUEST';
const GET_TAGS_REQUEST_START = 'tag/GET_TAGS_REQUEST_START';
const GET_TAGS_REQUEST_SUCCESS = 'tag/GET_TAGS_REQUEST_SUCCESS';
const GET_TAGS_REQUEST_FAILED = 'tag/GET_TAGS_REQUEST_FAILED';

export {
  GET_TAGS_REQUEST,
  GET_TAGS_REQUEST_START,
  GET_TAGS_REQUEST_SUCCESS,
  GET_TAGS_REQUEST_FAILED,
};
