// get all offers
const GET_OFFER_REQUEST = 'offer/GET_OFFER_REQUEST';
const GET_OFFER_REQUEST_START = 'offer/GET_OFFER_REQUEST_START';
const GET_OFFER_REQUEST_SUCCESS = 'offer/GET_OFFER_REQUEST_SUCCESS';
const GET_OFFER_REQUEST_FAILED = 'offer/GET_OFFER_REQUEST_FAILED';

export {
  GET_OFFER_REQUEST,
  GET_OFFER_REQUEST_START,
  GET_OFFER_REQUEST_SUCCESS,
  GET_OFFER_REQUEST_FAILED,
};
